FROM node:21 AS builder

WORKDIR /usr/src/app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY package*.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile --prod

COPY . .

FROM node:21 AS runner

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app /usr/src/app

ENV NODE_ENV=production

EXPOSE 3001

CMD ["pnpm", "run", "start:prod"]